name: test-workflow

on:
  workflow_dispatch:

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step 1
        run: echo "test step 1"
    
  test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List GitHub Issues and Write to File
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          GHP_ISSUES=$(gh issue list --label "github pages")
          LOG_ENTRY="$TIMESTAMP: $GHP_ISSUES" 
          echo $LOG_ENTRY >> testlogfile.txt
          cat testlogfile.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Log File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_logs
          path: testlogfile.txt
          retention-days: 7
