name: test-workflow

on:
  workflow_dispatch:

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step 1
        run: echo "test step 1"
    
  test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List GitHub Issues and Write to File
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          LOG_ENTRY="$TIMESTAMP: gh issue list --label \"github pages\"" 
          echo $LOG_ENTRY >> testtextfile.txt
          cat testtextfile.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
